<?php


namespace PHPML\Enum;

class KeyCode extends CDataEnum
{
    /*-------------
     * CSFML Type
     *-------------
     */

    const SF_KEY_UNKNOWN        = 'sfKeyUnknown';             ///< Unhandled key
    const SF_KEY_A              = 'sfKeyA';                   ///< The A key
    const SF_KEY_B              = 'sfKeyB';                   ///< The B key
    const SF_KEY_C              = 'sfKeyC';                   ///< The C key
    const SF_KEY_D              = 'sfKeyD';                   ///< The D key
    const SF_KEY_E              = 'sfKeyE';                   ///< The E key
    const SF_KEY_F              = 'sfKeyF';                   ///< The F key
    const SF_KEY_G              = 'sfKeyG';                   ///< The G key
    const SF_KEY_H              = 'sfKeyH';                   ///< The H key
    const SF_KEY_I              = 'sfKeyI';                   ///< The I key
    const SF_KEY_J              = 'sfKeyJ';                   ///< The J key
    const SF_KEY_K              = 'sfKeyK';                   ///< The K key
    const SF_KEY_L              = 'sfKeyL';                   ///< The L key
    const SF_KEY_M              = 'sfKeyM';                   ///< The M key
    const SF_KEY_N              = 'sfKeyN';                   ///< The N key
    const SF_KEY_O              = 'sfKeyO';                   ///< The O key
    const SF_KEY_P              = 'sfKeyP';                   ///< The P key
    const SF_KEY_Q              = 'sfKeyQ';                   ///< The Q key
    const SF_KEY_R              = 'sfKeyR';                   ///< The R key
    const SF_KEY_S              = 'sfKeyS';                   ///< The S key
    const SF_KEY_T              = 'sfKeyT';                   ///< The T key
    const SF_KEY_U              = 'sfKeyU';                   ///< The U key
    const SF_KEY_V              = 'sfKeyV';                   ///< The V key
    const SF_KEY_W              = 'sfKeyW';                   ///< The W key
    const SF_KEY_X              = 'sfKeyX';                   ///< The X key
    const SF_KEY_Y              = 'sfKeyY';                   ///< The Y key
    const SF_KEY_Z              = 'sfKeyZ';                   ///< The Z key
    const SF_KEY_0              = 'sfKeyNum0';                ///< The 0 key
    const SF_KEY_1              = 'sfKeyNum1';                ///< The 1 key
    const SF_KEY_2              = 'sfKeyNum2';                ///< The 2 key
    const SF_KEY_3              = 'sfKeyNum3';                ///< The 3 key
    const SF_KEY_4              = 'sfKeyNum4';                ///< The 4 key
    const SF_KEY_5              = 'sfKeyNum5';                ///< The 5 key
    const SF_KEY_6              = 'sfKeyNum6';                ///< The 6 key
    const SF_KEY_7              = 'sfKeyNum7';                ///< The 7 key
    const SF_KEY_8              = 'sfKeyNum8';                ///< The 8 key
    const SF_KEY_9              = 'sfKeyNum9';                ///< The 9 key
    const SF_KEY_ESCAPE         = 'sfKeyEscape';              ///< The Escape key
    const SF_KEY_LEFT_CONTROL   = 'sfKeyLControl';            ///< The left Control key
    const SF_KEY_LEFT_SHIFT     = 'sfKeyLShift';              ///< The left Shift key
    const SF_KEY_LEFT_ALT       = 'sfKeyLAlt';                ///< The left Alt key
    const SF_KEY_LEFT_SYSTEM    = 'sfKeyLSystem';             ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_RIGHT_CONTROL  = 'sfKeyRControl';            ///< The right Control key
    const SF_KEY_RIGHT_SHIFT    = 'sfKeyRShift';              ///< The right Shift key
    const SF_KEY_RIGHT_ALT      = 'sfKeyRAlt';                ///< The right Alt key
    const SF_KEY_RIGHT_SYSTEM   = 'sfKeyRSystem';             ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_MENU           = 'sfKeyMenu';                ///< The Menu key
    const SF_KEY_LEFT_BRACKET   = 'sfKeyLBracket';            ///< The [ key
    const SF_KEY_RIGHT_BRACKET  = 'sfKeyRBracket';            ///< The ] key
    const SF_KEY_SEMICOLON      = 'sfKeySemicolon';           ///< The ; key
    const SF_KEY_COMMA          = 'sfKeyComma';               ///< 'The '; key
    const SF_KEY_PERIOD         = 'sfKeyPeriod';              ///< The . key
    const SF_KEY_QUOTE          = 'sfKeyQuote';               ///< The ' key
    const SF_KEY_SLASH          = 'sfKeySlash';               ///< The / key
    const SF_KEY_BACK_SLASH     = 'sfKeyBackslash';           ///< The \ key
    const SF_KEY_TILDE          = 'sfKeyTilde';               ///< The ~ key
    const SF_KEY_EQUAL          = 'sfKeyEqual';               ///< The = key
    const SF_KEY_HYPHEN         = 'sfKeyHyphen';              ///< The - key (hyphen)
    const SF_KEY_SPACE          = 'sfKeySpace';               ///< The Space key
    const SF_KEY_ENTER          = 'sfKeyEnter';               ///< The Enter/Return key
    const SF_KEY_BACKSPACE      = 'sfKeyBackspace';           ///< The Backspace key
    const SF_KEY_TAB            = 'sfKeyTab';                 ///< The Tabulation key
    const SF_KEY_PAGEUP         = 'sfKeyPageUp';              ///< The Page up key
    const SF_KEY_PAGEDOWN       = 'sfKeyPageDown';            ///< The Page down key
    const SF_KEY_END            = 'sfKeyEnd';                 ///< The End key
    const SF_KEY_HOME           = 'sfKeyHome';                ///< The Home key
    const SF_KEY_INSERT         = 'sfKeyInsert';              ///< The Insert key
    const SF_KEY_DELETE         = 'sfKeyDelete';              ///< The Delete key
    const SF_KEY_ADD            = 'sfKeyAdd';                 ///< The + key
    const SF_KEY_SUBTRACT       = 'sfKeySubtract';            ///< The - key ('minus'; usually from numpad)
    const SF_KEY_MULTIPLY       = 'sfKeyMultiply';            ///< The * key
    const SF_KEY_DIVIDE         = 'sfKeyDivide';              ///< The / key
    const SF_KEY_LEFT           = 'sfKeyLeft';                ///< Left arrow
    const SF_KEY_RIGHT          = 'sfKeyRight';               ///< Right arrow
    const SF_KEY_UP             = 'sfKeyUp';                  ///< Up arrow
    const SF_KEY_DOWN           = 'sfKeyDown';                ///< Down arrow
    const SF_KEY_NUMPAD_0       = 'sfKeyNumpad0';             ///< The numpad 0 key
    const SF_KEY_NUMPAD_1       = 'sfKeyNumpad1';             ///< The numpad 1 key
    const SF_KEY_NUMPAD_2       = 'sfKeyNumpad2';             ///< The numpad 2 key
    const SF_KEY_NUMPAD_3       = 'sfKeyNumpad3';             ///< The numpad 3 key
    const SF_KEY_NUMPAD_4       = 'sfKeyNumpad4';             ///< The numpad 4 key
    const SF_KEY_NUMPAD_5       = 'sfKeyNumpad5';             ///< The numpad 5 key
    const SF_KEY_NUMPAD_6       = 'sfKeyNumpad6';             ///< The numpad 6 key
    const SF_KEY_NUMPAD_7       = 'sfKeyNumpad7';             ///< The numpad 7 key
    const SF_KEY_NUMPAD_8       = 'sfKeyNumpad8';             ///< The numpad 8 key
    const SF_KEY_NUMPAD_9       = 'sfKeyNumpad9';             ///< The numpad 9 key
    const SF_KEY_F1             = 'sfKeyF1';                  ///< The F1 key
    const SF_KEY_F2             = 'sfKeyF2';                  ///< The F2 key
    const SF_KEY_F3             = 'sfKeyF3';                  ///< The F3 key
    const SF_KEY_F4             = 'sfKeyF4';                  ///< The F4 key
    const SF_KEY_F5             = 'sfKeyF5';                  ///< The F5 key
    const SF_KEY_F6             = 'sfKeyF6';                  ///< The F6 key
    const SF_KEY_F7             = 'sfKeyF7';                  ///< The F7 key
    const SF_KEY_F8             = 'sfKeyF8';                  ///< The F8 key
    const SF_KEY_F9             = 'sfKeyF9';                  ///< The F8 key
    const SF_KEY_F10            = 'sfKeyF10';                 ///< The F10 key
    const SF_KEY_F11            = 'sfKeyF11';                 ///< The F11 key
    const SF_KEY_F12            = 'sfKeyF12';                 ///< The F12 key
    const SF_KEY_F13            = 'sfKeyF13';                 ///< The F13 key
    const SF_KEY_F14            = 'sfKeyF14';                 ///< The F14 key
    const SF_KEY_F15            = 'sfKeyF15';                 ///< The F15 key
    const SF_KEY_PAUSE          = 'sfKeyPause';               ///< The Pause key

    /*-------------
     * CSFML Enum
     *-------------
     */

    const UNKNOWN       = -1;                       ///< Unhandled key
    const KEY_A             = 0;                        ///< The A key
    const KEY_B             = 1;                        ///< The B key
    const KEY_C             = 2;                        ///< The C key
    const KEY_D             = 3;                        ///< The D key
    const KEY_E             = 4;                        ///< The E key
    const KEY_F             = 5;                        ///< The F key
    const KEY_G             = 6;                        ///< The G key
    const KEY_H             = 7;                        ///< The H key
    const KEY_I             = 8;                        ///< The I key
    const KEY_J             = 9;                        ///< The J key
    const KEY_K             = 10;                       ///< The K key
    const KEY_L             = 11;                       ///< The L key
    const KEY_M             = 12;                       ///< The M key
    const KEY_N             = 13;                       ///< The N key
    const KEY_O             = 14;                       ///< The O key
    const KEY_P             = 15;                       ///< The P key
    const KEY_Q             = 16;                       ///< The Q key
    const KEY_R             = 17;                       ///< The R key
    const KEY_S             = 18;                       ///< The S key
    const KEY_T             = 19;                       ///< The T key
    const KEY_U             = 20;                       ///< The U key
    const KEY_V             = 21;                       ///< The V key
    const KEY_W             = 22;                       ///< The W key
    const KEY_X             = 23;                       ///< The X key
    const KEY_Y             = 24;                       ///< The Y key
    const KEY_Z             = 25;                       ///< The Z key
    const KEY_ZERO          = 26;                       ///< The 0 key
    const KEY_ONE           = 27;                       ///< The 1 key
    const KEY_TWO           = 28;                       ///< The 2 key
    const KEY_THREE         = 29;                       ///< The 3 key
    const KEY_FOUR          = 30;                       ///< The 4 key
    const KEY_FIVE          = 31;                       ///< The 5 key
    const KEY_SIX           = 32;                       ///< The 6 key
    const KEY_SEVEN         = 33;                       ///< The 7 key
    const KEY_EIGHT         = 34;                       ///< The 8 key
    const KEY_NINE          = 35;                       ///< The 9 key
    const KEY_ESCAPE        = 36;                       ///< The Escape key
    const KEY_LEFT_CONTROL  = 37;                       ///< The left Control key
    const KEY_LEFT_SHIFT    = 38;                       ///< The left Shift key
    const KEY_LEFT_ALT      = 39;                       ///< The left Alt key
    const KEY_LEFT_SYSTEM   = 40;                       ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const KEY_RIGHT_CONTROL = 41;                       ///< The right Control key
    const KEY_RIGHT_SHIFT   = 42;                       ///< The right Shift key
    const KEY_RIGHT_ALT     = 43;                       ///< The right Alt key
    const KEY_RIGHT_SYSTEM  = 44;                       ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const KEY_MENU          = 45;                       ///< The Menu key
    const KEY_LEFT_BRACKET  = 46;                       ///< The [ key
    const KEY_RIGHT_BRACKET = 47;                       ///< The ] key
    const KEY_SEMICOLON     = 48;                       ///< The ; key
    const KEY_COMMA         = 49;                       ///< 'The '; key
    const KEY_PERIOD        = 50;                       ///< The . key
    const KEY_QUOTE         = 51;                       ///< The ' key
    const KEY_SLASH         = 52;                       ///< The / key
    const KEY_BACK_SLASH    = 53;                       ///< The \ key
    const KEY_TILDE         = 54;                       ///< The ~ key
    const KEY_EQUAL         = 55;                       ///< The = key
    const KEY_HYPHEN        = 56;                       ///< The - key (hyphen)
    const KEY_SPACE         = 57;                       ///< The Space key
    const KEY_ENTER         = 58;                       ///< The Enter/Return key
    const KEY_BACKSPACE     = 59;                       ///< The Backspace key
    const KEY_TAB           = 60;                       ///< The Tabulation key
    const KEY_PAGEUP        = 61;                       ///< The Page up key
    const KEY_PAGEDOWN      = 62;                       ///< The Page down key
    const KEY_END           = 63;                       ///< The End key
    const KEY_HOME          = 64;                       ///< The Home key
    const KEY_INSERT        = 65;                       ///< The Insert key
    const KEY_DELETE        = 66;                       ///< The Delete key
    const KEY_ADD           = 67;                       ///< The + key
    const KEY_SUBTRACT      = 68;                       ///< The - key ('minus'; usually from numpad)
    const KEY_MULTIPLY      = 69;                       ///< The * key
    const KEY_DIVIDE        = 70;                       ///< The / key
    const KEY_LEFT          = 71;                       ///< Left arrow
    const KEY_RIGHT         = 72;                       ///< Right arrow
    const KEY_UP            = 73;                       ///< Up arrow
    const KEY_DOWN          = 74;                       ///< Down arrow
    const KEY_NUMPAD_0      = 75;                       ///< The numpad 0 key
    const KEY_NUMPAD_1      = 76;                       ///< The numpad 1 key
    const KEY_NUMPAD_2      = 77;                       ///< The numpad 2 key
    const KEY_NUMPAD_3      = 78;                       ///< The numpad 3 key
    const KEY_NUMPAD_4      = 79;                       ///< The numpad 4 key
    const KEY_NUMPAD_5      = 80;                       ///< The numpad 5 key
    const KEY_NUMPAD_6      = 81;                       ///< The numpad 6 key
    const KEY_NUMPAD_7      = 82;                       ///< The numpad 7 key
    const KEY_NUMPAD_8      = 83;                       ///< The numpad 8 key
    const KEY_NUMPAD_9      = 84;                       ///< The numpad 9 key
    const KEY_F1            = 85;                       ///< The F1 key
    const KEY_F2            = 86;                       ///< The F2 key
    const KEY_F3            = 87;                       ///< The F3 key
    const KEY_F4            = 88;                       ///< The F4 key
    const KEY_F5            = 89;                       ///< The F5 key
    const KEY_F6            = 90;                       ///< The F6 key
    const KEY_F7            = 91;                       ///< The F7 key
    const KEY_F8            = 92;                       ///< The F8 key
    const KEY_F9            = 93;                       ///< The F8 key
    const KEY_F10           = 94;                       ///< The F10 key
    const KEY_F11           = 95;                       ///< The F11 key
    const KEY_F12           = 96;                       ///< The F12 key
    const KEY_F13           = 97;                       ///< The F13 key
    const KEY_F14           = 98;                       ///< The F14 key
    const KEY_F15           = 99;                       ///< The F15 key
    const KEY_PAUSE         = 100;                      ///< The Pause key

    /*----------
     * Association Enum-Type
     *----------
     */

    const CODE_TYPE = [
        self::KEY_A                     => self::SF_KEY_A,
        self::KEY_B                     => self::SF_KEY_B,
        self::KEY_C                     => self::SF_KEY_C,
        self::KEY_D                     => self::SF_KEY_D,
        self::KEY_E                     => self::SF_KEY_E,
        self::KEY_F                     => self::SF_KEY_F,
        self::KEY_G                     => self::SF_KEY_G,
        self::KEY_H                     => self::SF_KEY_H,
        self::KEY_I                     => self::SF_KEY_I,
        self::KEY_J                     => self::SF_KEY_J,
        self::KEY_K                     => self::SF_KEY_K,
        self::KEY_L                     => self::SF_KEY_L,
        self::KEY_M                     => self::SF_KEY_M,
        self::KEY_N                     => self::SF_KEY_N,
        self::KEY_O                     => self::SF_KEY_O,
        self::KEY_P                     => self::SF_KEY_P,
        self::KEY_Q                     => self::SF_KEY_Q,
        self::KEY_R                     => self::SF_KEY_R,
        self::KEY_S                     => self::SF_KEY_S,
        self::KEY_T                     => self::SF_KEY_T,
        self::KEY_U                     => self::SF_KEY_U,
        self::KEY_V                     => self::SF_KEY_V,
        self::KEY_W                     => self::SF_KEY_W,
        self::KEY_X                     => self::SF_KEY_X,
        self::KEY_Y                     => self::SF_KEY_Y,
        self::KEY_Z                     => self::SF_KEY_Z,
        self::KEY_ZERO                  => self::SF_KEY_0,
        self::KEY_ONE                   => self::SF_KEY_1,
        self::KEY_TWO                   => self::SF_KEY_2,
        self::KEY_THREE                 => self::SF_KEY_3,
        self::KEY_FOUR                  => self::SF_KEY_4,
        self::KEY_FIVE                  => self::SF_KEY_5,
        self::KEY_SIX                   => self::SF_KEY_6,
        self::KEY_SEVEN                 => self::SF_KEY_7,
        self::KEY_EIGHT                 => self::SF_KEY_8,
        self::KEY_NINE                  => self::SF_KEY_9,
        self::KEY_ESCAPE                => self::SF_KEY_ESCAPE,
        self::KEY_LEFT_CONTROL          => self::SF_KEY_LEFT_CONTROL,
        self::KEY_LEFT_SHIFT            => self::SF_KEY_LEFT_SHIFT,
        self::KEY_LEFT_ALT              => self::SF_KEY_LEFT_ALT,
        self::KEY_LEFT_SYSTEM           => self::SF_KEY_LEFT_SYSTEM,
        self::KEY_RIGHT_CONTROL         => self::SF_KEY_RIGHT_CONTROL,
        self::KEY_RIGHT_SHIFT           => self::SF_KEY_RIGHT_SHIFT,
        self::KEY_RIGHT_ALT             => self::SF_KEY_RIGHT_ALT,
        self::KEY_RIGHT_SYSTEM          => self::SF_KEY_RIGHT_SYSTEM,
        self::KEY_MENU                  => self::SF_KEY_MENU,
        self::KEY_LEFT_BRACKET          => self::SF_KEY_LEFT_BRACKET,
        self::KEY_RIGHT_BRACKET         => self::SF_KEY_RIGHT_BRACKET,
        self::KEY_SEMICOLON             => self::SF_KEY_SEMICOLON,
        self::KEY_COMMA                 => self::SF_KEY_COMMA,
        self::KEY_PERIOD                => self::SF_KEY_PERIOD,
        self::KEY_QUOTE                 => self::SF_KEY_QUOTE,
        self::KEY_SLASH                 => self::SF_KEY_SLASH,
        self::KEY_BACK_SLASH            => self::SF_KEY_BACK_SLASH,
        self::KEY_TILDE                 => self::SF_KEY_TILDE,
        self::KEY_EQUAL                 => self::SF_KEY_EQUAL,
        self::KEY_HYPHEN                => self::SF_KEY_HYPHEN,
        self::KEY_SPACE                 => self::SF_KEY_SPACE,
        self::KEY_ENTER                 => self::SF_KEY_ENTER,
        self::KEY_BACKSPACE             => self::SF_KEY_BACKSPACE,
        self::KEY_TAB                   => self::SF_KEY_TAB,
        self::KEY_PAGEUP                => self::SF_KEY_PAGEUP,
        self::KEY_PAGEDOWN              => self::SF_KEY_PAGEDOWN,
        self::KEY_END                   => self::SF_KEY_END,
        self::KEY_HOME                  => self::SF_KEY_HOME,
        self::KEY_INSERT                => self::SF_KEY_INSERT,
        self::KEY_DELETE                => self::SF_KEY_DELETE,
        self::KEY_ADD                   => self::SF_KEY_ADD,
        self::KEY_SUBTRACT              => self::SF_KEY_SUBTRACT,
        self::KEY_MULTIPLY              => self::SF_KEY_MULTIPLY,
        self::KEY_DIVIDE                => self::SF_KEY_DIVIDE,
        self::KEY_LEFT                  => self::SF_KEY_LEFT,
        self::KEY_RIGHT                 => self::SF_KEY_RIGHT,
        self::KEY_UP                    => self::SF_KEY_UP,
        self::KEY_DOWN                  => self::SF_KEY_DOWN,
        self::KEY_NUMPAD_0              => self::SF_KEY_NUMPAD_0,
        self::KEY_NUMPAD_1              => self::SF_KEY_NUMPAD_1,
        self::KEY_NUMPAD_2              => self::SF_KEY_NUMPAD_2,
        self::KEY_NUMPAD_3              => self::SF_KEY_NUMPAD_3,
        self::KEY_NUMPAD_4              => self::SF_KEY_NUMPAD_4,
        self::KEY_NUMPAD_5              => self::SF_KEY_NUMPAD_5,
        self::KEY_NUMPAD_6              => self::SF_KEY_NUMPAD_6,
        self::KEY_NUMPAD_7              => self::SF_KEY_NUMPAD_7,
        self::KEY_NUMPAD_8              => self::SF_KEY_NUMPAD_8,
        self::KEY_NUMPAD_9              => self::SF_KEY_NUMPAD_9,
        self::KEY_F1                    => self::SF_KEY_F1,
        self::KEY_F2                    => self::SF_KEY_F2,
        self::KEY_F3                    => self::SF_KEY_F3,
        self::KEY_F4                    => self::SF_KEY_F4,
        self::KEY_F5                    => self::SF_KEY_F5,
        self::KEY_F6                    => self::SF_KEY_F6,
        self::KEY_F7                    => self::SF_KEY_F7,
        self::KEY_F8                    => self::SF_KEY_F8,
        self::KEY_F9                    => self::SF_KEY_F9,
        self::KEY_F10                   => self::SF_KEY_F10,
        self::KEY_F11                   => self::SF_KEY_F11,
        self::KEY_F12                   => self::SF_KEY_F12,
        self::KEY_F13                   => self::SF_KEY_F13,
        self::KEY_F14                   => self::SF_KEY_F14,
        self::KEY_F15                   => self::SF_KEY_F15,
        self::KEY_PAUSE                 => self::SF_KEY_PAUSE,
    ];
}
