<?php


namespace PHPML\Enum;

class KeyCode extends CDataEnum
{
    const SF_KEY_UNKNOWN = 'sfKeyUnknown';              ///< Unhandled key
    const SF_KEY_A = 'sfKeyA';                          ///< The A key
    const SF_KEY_B = 'sfKeyB';                          ///< The B key
    const SF_KEY_C = 'sfKeyC';                          ///< The C key
    const SF_KEY_D = 'sfKeyD';                          ///< The D key
    const SF_KEY_E = 'sfKeyE';                          ///< The E key
    const SF_KEY_F = 'sfKeyF';                          ///< The F key
    const SF_KEY_G = 'sfKeyG';                          ///< The G key
    const SF_KEY_H = 'sfKeyH';                          ///< The H key
    const SF_KEY_I = 'sfKeyI';                          ///< The I key
    const SF_KEY_J = 'sfKeyJ';                          ///< The J key
    const SF_KEY_K = 'sfKeyK';                          ///< The K key
    const SF_KEY_L = 'sfKeyL';                          ///< The L key
    const SF_KEY_M = 'sfKeyM';                          ///< The M key
    const SF_KEY_N = 'sfKeyN';                          ///< The N key
    const SF_KEY_O = 'sfKeyO';                          ///< The O key
    const SF_KEY_P = 'sfKeyP';                          ///< The P key
    const SF_KEY_Q = 'sfKeyQ';                          ///< The Q key
    const SF_KEY_R = 'sfKeyR';                          ///< The R key
    const SF_KEY_S = 'sfKeyS';                          ///< The S key
    const SF_KEY_T = 'sfKeyT';                          ///< The T key
    const SF_KEY_U = 'sfKeyU';                          ///< The U key
    const SF_KEY_V = 'sfKeyV';                          ///< The V key
    const SF_KEY_W = 'sfKeyW';                          ///< The W key
    const SF_KEY_X = 'sfKeyX';                          ///< The X key
    const SF_KEY_Y = 'sfKeyY';                          ///< The Y key
    const SF_KEY_Z = 'sfKeyZ';                          ///< The Z key
    const SF_KEY_0 = 'sfKeyNum0';                       ///< The 0 key
    const SF_KEY_1 = 'sfKeyNum1';                       ///< The 1 key
    const SF_KEY_2 = 'sfKeyNum2';                       ///< The 2 key
    const SF_KEY_3 = 'sfKeyNum3';                       ///< The 3 key
    const SF_KEY_4 = 'sfKeyNum4';                       ///< The 4 key
    const SF_KEY_5 = 'sfKeyNum5';                       ///< The 5 key
    const SF_KEY_6 = 'sfKeyNum6';                       ///< The 6 key
    const SF_KEY_7 = 'sfKeyNum7';                       ///< The 7 key
    const SF_KEY_8 = 'sfKeyNum8';                       ///< The 8 key
    const SF_KEY_9 = 'sfKeyNum9';                       ///< The 9 key
    const SF_KEY_ESCAPE = 'sfKeyEscape';                ///< The Escape key
    const SF_KEY_LEFT_CONTROL = 'sfKeyLControl';        ///< The left Control key
    const SF_KEY_LEFT_SHIFT = 'sfKeyLShift';            ///< The left Shift key
    const SF_KEY_LEFT_ALT = 'sfKeyLAlt';                ///< The left Alt key
    const SF_KEY_LEFT_SYSTEM = 'sfKeyLSystem';          ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_RIGHT_CONTROL = 'sfKeyRControl';       ///< The right Control key
    const SF_KEY_RIGHT_SHIFT = 'sfKeyRShift';           ///< The right Shift key
    const SF_KEY_RIGHT_ALT = 'sfKeyRAlt';               ///< The right Alt key
    const SF_KEY_RIGHT_SYSTEM = 'sfKeyRSystem';         ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_MENU = 'sfKeyMenu';                    ///< The Menu key
    const SF_KEY_LEFT_BRACKET = 'sfKeyLBracket';        ///< The [ key
    const SF_KEY_RIGHT_BRACKET = 'sfKeyRBracket';       ///< The ] key
    const SF_KEY_SEMICOLON = 'sfKeySemicolon';          ///< The ; key
    const SF_KEY_COMMA = 'sfKeyComma';                  ///< 'The '; key
    const SF_KEY_PERIOD = 'sfKeyPeriod';                ///< The . key
    const SF_KEY_QUOTE = 'sfKeyQuote';                  ///< The ' key
    const SF_KEY_SLASH = 'sfKeySlash';                  ///< The / key
    const SF_KEY_BACK_SLASH = 'sfKeyBackslash';         ///< The \ key
    const SF_KEY_TILDE = 'sfKeyTilde';                  ///< The ~ key
    const SF_KEY_EQUAL = 'sfKeyEqual';                  ///< The = key
    const SF_KEY_HYPHEN = 'sfKeyHyphen';                ///< The - key (hyphen)
    const SF_KEY_SPACE = 'sfKeySpace';                  ///< The Space key
    const SF_KEY_ENTER = 'sfKeyEnter';                  ///< The Enter/Return key
    const SF_KEY_BACKSPACE = 'sfKeyBackspace';          ///< The Backspace key
    const SF_KEY_TAB = 'sfKeyTab';                      ///< The Tabulation key
    const SF_KEY_PAGEUP = 'sfKeyPageUp';                ///< The Page up key
    const SF_KEY_PAGEDOWN = 'sfKeyPageDown';            ///< The Page down key
    const SF_KEY_END = 'sfKeyEnd';                      ///< The End key
    const SF_KEY_HOME = 'sfKeyHome';                    ///< The Home key
    const SF_KEY_INSERT = 'sfKeyInsert';                ///< The Insert key
    const SF_KEY_DELETE = 'sfKeyDelete';                ///< The Delete key
    const SF_KEY_ADD = 'sfKeyAdd';                      ///< The + key
    const SF_KEY_SUBTRACT = 'sfKeySubtract';            ///< The - key ('minus'; usually from numpad)
    const SF_KEY_MULTIPLY = 'sfKeyMultiply';            ///< The * key
    const SF_KEY_DIVIDE = 'sfKeyDivide';                ///< The / key
    const SF_KEY_LEFT = 'sfKeyLeft';                    ///< Left arrow
    const SF_KEY_RIGHT = 'sfKeyRight';                  ///< Right arrow
    const SF_KEY_UP = 'sfKeyUp';                        ///< Up arrow
    const SF_KEY_DOWN = 'sfKeyDown';                    ///< Down arrow
    const SF_KEY_NUMPAD_0 = 'sfKeyNumpad0';             ///< The numpad 0 key
    const SF_KEY_NUMPAD_1 = 'sfKeyNumpad1';             ///< The numpad 1 key
    const SF_KEY_NUMPAD_2 = 'sfKeyNumpad2';             ///< The numpad 2 key
    const SF_KEY_NUMPAD_3 = 'sfKeyNumpad3';             ///< The numpad 3 key
    const SF_KEY_NUMPAD_4 = 'sfKeyNumpad4';             ///< The numpad 4 key
    const SF_KEY_NUMPAD_5 = 'sfKeyNumpad5';             ///< The numpad 5 key
    const SF_KEY_NUMPAD_6 = 'sfKeyNumpad6';             ///< The numpad 6 key
    const SF_KEY_NUMPAD_7 = 'sfKeyNumpad7';             ///< The numpad 7 key
    const SF_KEY_NUMPAD_8 = 'sfKeyNumpad8';             ///< The numpad 8 key
    const SF_KEY_NUMPAD_9 = 'sfKeyNumpad9';             ///< The numpad 9 key
    const SF_KEY_F1 = 'sfKeyF1';                        ///< The F1 key
    const SF_KEY_F2 = 'sfKeyF2';                        ///< The F2 key
    const SF_KEY_F3 = 'sfKeyF3';                        ///< The F3 key
    const SF_KEY_F4 = 'sfKeyF4';                        ///< The F4 key
    const SF_KEY_F5 = 'sfKeyF5';                        ///< The F5 key
    const SF_KEY_F6 = 'sfKeyF6';                        ///< The F6 key
    const SF_KEY_F7 = 'sfKeyF7';                        ///< The F7 key
    const SF_KEY_F8 = 'sfKeyF8';                        ///< The F8 key
    const SF_KEY_F9 = 'sfKeyF9';                        ///< The F8 key
    const SF_KEY_F10 = 'sfKeyF10';                      ///< The F10 key
    const SF_KEY_F11 = 'sfKeyF11';                      ///< The F11 key
    const SF_KEY_F12 = 'sfKeyF12';                      ///< The F12 key
    const SF_KEY_F13 = 'sfKeyF13';                      ///< The F13 key
    const SF_KEY_F14 = 'sfKeyF14';                      ///< The F14 key
    const SF_KEY_F15 = 'sfKeyF15';                      ///< The F15 key
    const SF_KEY_PAUSE = 'sfKeyPause';                  ///< The Pause key

    const UNKNOWN = -1;              ///< Unhandled key
    const A = 1;                          ///< The A key
    const B = 2;                          ///< The B key
    const C = 3;                          ///< The C key
    const D = 4;                          ///< The D key
    const E = 5;                          ///< The E key
    const F = 6;                          ///< The F key
    const G = 7;                          ///< The G key
    const H = 8;                          ///< The H key
    const I = 9;                          ///< The I key
    const J = 10;                          ///< The J key
    const K = 11;                          ///< The K key
    const L = 12;                          ///< The L key
    const M = 13;                          ///< The M key
    const N = 14;                          ///< The N key
    const O = 15;                          ///< The O key
    const P = 16;                          ///< The P key
    const Q = 17;                          ///< The Q key
    const R = 18;                          ///< The R key
    const S = 19;                          ///< The S key
    const T = 20;                          ///< The T key
    const U = 21;                          ///< The U key
    const V = 22;                          ///< The V key
    const W = 23;                          ///< The W key
    const X = 24;                          ///< The X key
    const Y = 25;                          ///< The Y key
    const Z = 26;                          ///< The Z key
    const ZERO = 27;                       ///< The 0 key
    const ONE  = 28;                       ///< The 1 key
    const TWO = 29;                       ///< The 2 key
    const THREE = 30;                       ///< The 3 key
    const FOUR = 31;                       ///< The 4 key
    const FIVE = 32;                       ///< The 5 key
    const SIX = 33;                       ///< The 6 key
    const SEVEN = 34;                       ///< The 7 key
    const EIGHT = 35;                       ///< The 8 key
    const NINE = 36;                       ///< The 9 key
    const ESCAPE = 37;                ///< The Escape key
    const LEFT_CONTROL = 38;        ///< The left Control key
    const LEFT_SHIFT = 39;            ///< The left Shift key
    const LEFT_ALT = 40;                ///< The left Alt key
    const LEFT_SYSTEM = 41;          ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const RIGHT_CONTROL = 42;       ///< The right Control key
    const RIGHT_SHIFT = 43;           ///< The right Shift key
    const RIGHT_ALT = 44;               ///< The right Alt key
    const RIGHT_SYSTEM = 45;         ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const MENU = 46;                    ///< The Menu key
    const LEFT_BRACKET = 47;        ///< The [ key
    const RIGHT_BRACKET = 48;       ///< The ] key
    const SEMICOLON = 49;          ///< The ; key
    const COMMA = 50;                  ///< 'The '; key
    const PERIOD = 51;                ///< The . key
    const QUOTE = 52;                  ///< The ' key
    const SLASH = 53;                  ///< The / key
    const BACK_SLASH = 54;         ///< The \ key
    const TILDE = 55;                  ///< The ~ key
    const EQUAL = 56;                  ///< The = key
    const HYPHEN = 57;                ///< The - key (hyphen)
    const SPACE = 58;                  ///< The Space key
    const ENTER = 59;                  ///< The Enter/Return key
    const BACKSPACE = 60;          ///< The Backspace key
    const TAB = 61;                      ///< The Tabulation key
    const PAGEUP = 62;                ///< The Page up key
    const PAGEDOWN = 63;            ///< The Page down key
    const END = 64;                      ///< The End key
    const HOME = 65;                    ///< The Home key
    const INSERT = 66;                ///< The Insert key
    const DELETE = 67;                ///< The Delete key
    const ADD = 68;                      ///< The + key
    const SUBTRACT = 69;            ///< The - key ('minus'; usually from numpad)
    const MULTIPLY = 70;            ///< The * key
    const DIVIDE = 71;                ///< The / key
    const LEFT = 72;                    ///< Left arrow
    const RIGHT = 73;                  ///< Right arrow
    const UP = 74;                        ///< Up arrow
    const DOWN = 75;                    ///< Down arrow
    const NUMPAD_0 = 76;             ///< The numpad 0 key
    const NUMPAD_1 = 77;             ///< The numpad 1 key
    const NUMPAD_2 = 78;             ///< The numpad 2 key
    const NUMPAD_3 = 79;             ///< The numpad 3 key
    const NUMPAD_4 = 80;             ///< The numpad 4 key
    const NUMPAD_5 = 81;             ///< The numpad 5 key
    const NUMPAD_6 = 82;             ///< The numpad 6 key
    const NUMPAD_7 = 83;             ///< The numpad 7 key
    const NUMPAD_8 = 84;             ///< The numpad 8 key
    const NUMPAD_9 = 85;             ///< The numpad 9 key
    const F1 = 86;                        ///< The F1 key
    const F2 = 87;                        ///< The F2 key
    const F3 = 88;                        ///< The F3 key
    const F4 = 89;                        ///< The F4 key
    const F5 = 90;                        ///< The F5 key
    const F6 = 91;                        ///< The F6 key
    const F7 = 92;                        ///< The F7 key
    const F8 = 93;                        ///< The F8 key
    const F9 = 94;                        ///< The F8 key
    const F10 = 95;                      ///< The F10 key
    const F11 = 96;                      ///< The F11 key
    const F12 = 97;                      ///< The F12 key
    const F13 = 98;                      ///< The F13 key
    const F14 = 99;                      ///< The F14 key
    const F15 = 100;                      ///< The F15 key
    const PAUSE = 101;                  ///< The Pause key
}
