<?php


namespace PHPML\Enum;

class KeyCode extends CDataEnum
{
    /*-------------
     * CSFML Type
     *-------------
     */

    const SF_KEY_UNKNOWN        = 'sfKeyUnknown';             ///< Unhandled key
    const SF_KEY_A              = 'sfKeyA';                   ///< The A key
    const SF_KEY_B              = 'sfKeyB';                   ///< The B key
    const SF_KEY_C              = 'sfKeyC';                   ///< The C key
    const SF_KEY_D              = 'sfKeyD';                   ///< The D key
    const SF_KEY_E              = 'sfKeyE';                   ///< The E key
    const SF_KEY_F              = 'sfKeyF';                   ///< The F key
    const SF_KEY_G              = 'sfKeyG';                   ///< The G key
    const SF_KEY_H              = 'sfKeyH';                   ///< The H key
    const SF_KEY_I              = 'sfKeyI';                   ///< The I key
    const SF_KEY_J              = 'sfKeyJ';                   ///< The J key
    const SF_KEY_K              = 'sfKeyK';                   ///< The K key
    const SF_KEY_L              = 'sfKeyL';                   ///< The L key
    const SF_KEY_M              = 'sfKeyM';                   ///< The M key
    const SF_KEY_N              = 'sfKeyN';                   ///< The N key
    const SF_KEY_O              = 'sfKeyO';                   ///< The O key
    const SF_KEY_P              = 'sfKeyP';                   ///< The P key
    const SF_KEY_Q              = 'sfKeyQ';                   ///< The Q key
    const SF_KEY_R              = 'sfKeyR';                   ///< The R key
    const SF_KEY_S              = 'sfKeyS';                   ///< The S key
    const SF_KEY_T              = 'sfKeyT';                   ///< The T key
    const SF_KEY_U              = 'sfKeyU';                   ///< The U key
    const SF_KEY_V              = 'sfKeyV';                   ///< The V key
    const SF_KEY_W              = 'sfKeyW';                   ///< The W key
    const SF_KEY_X              = 'sfKeyX';                   ///< The X key
    const SF_KEY_Y              = 'sfKeyY';                   ///< The Y key
    const SF_KEY_Z              = 'sfKeyZ';                   ///< The Z key
    const SF_KEY_0              = 'sfKeyNum0';                ///< The 0 key
    const SF_KEY_1              = 'sfKeyNum1';                ///< The 1 key
    const SF_KEY_2              = 'sfKeyNum2';                ///< The 2 key
    const SF_KEY_3              = 'sfKeyNum3';                ///< The 3 key
    const SF_KEY_4              = 'sfKeyNum4';                ///< The 4 key
    const SF_KEY_5              = 'sfKeyNum5';                ///< The 5 key
    const SF_KEY_6              = 'sfKeyNum6';                ///< The 6 key
    const SF_KEY_7              = 'sfKeyNum7';                ///< The 7 key
    const SF_KEY_8              = 'sfKeyNum8';                ///< The 8 key
    const SF_KEY_9              = 'sfKeyNum9';                ///< The 9 key
    const SF_KEY_ESCAPE         = 'sfKeyEscape';              ///< The Escape key
    const SF_KEY_LEFT_CONTROL   = 'sfKeyLControl';            ///< The left Control key
    const SF_KEY_LEFT_SHIFT     = 'sfKeyLShift';              ///< The left Shift key
    const SF_KEY_LEFT_ALT       = 'sfKeyLAlt';                ///< The left Alt key
    const SF_KEY_LEFT_SYSTEM    = 'sfKeyLSystem';             ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_RIGHT_CONTROL  = 'sfKeyRControl';            ///< The right Control key
    const SF_KEY_RIGHT_SHIFT    = 'sfKeyRShift';              ///< The right Shift key
    const SF_KEY_RIGHT_ALT      = 'sfKeyRAlt';                ///< The right Alt key
    const SF_KEY_RIGHT_SYSTEM   = 'sfKeyRSystem';             ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const SF_KEY_MENU           = 'sfKeyMenu';                ///< The Menu key
    const SF_KEY_LEFT_BRACKET   = 'sfKeyLBracket';            ///< The [ key
    const SF_KEY_RIGHT_BRACKET  = 'sfKeyRBracket';            ///< The ] key
    const SF_KEY_SEMICOLON      = 'sfKeySemicolon';           ///< The ; key
    const SF_KEY_COMMA          = 'sfKeyComma';               ///< 'The '; key
    const SF_KEY_PERIOD         = 'sfKeyPeriod';              ///< The . key
    const SF_KEY_QUOTE          = 'sfKeyQuote';               ///< The ' key
    const SF_KEY_SLASH          = 'sfKeySlash';               ///< The / key
    const SF_KEY_BACK_SLASH     = 'sfKeyBackslash';           ///< The \ key
    const SF_KEY_TILDE          = 'sfKeyTilde';               ///< The ~ key
    const SF_KEY_EQUAL          = 'sfKeyEqual';               ///< The = key
    const SF_KEY_HYPHEN         = 'sfKeyHyphen';              ///< The - key (hyphen)
    const SF_KEY_SPACE          = 'sfKeySpace';               ///< The Space key
    const SF_KEY_ENTER          = 'sfKeyEnter';               ///< The Enter/Return key
    const SF_KEY_BACKSPACE      = 'sfKeyBackspace';           ///< The Backspace key
    const SF_KEY_TAB            = 'sfKeyTab';                 ///< The Tabulation key
    const SF_KEY_PAGEUP         = 'sfKeyPageUp';              ///< The Page up key
    const SF_KEY_PAGEDOWN       = 'sfKeyPageDown';            ///< The Page down key
    const SF_KEY_END            = 'sfKeyEnd';                 ///< The End key
    const SF_KEY_HOME           = 'sfKeyHome';                ///< The Home key
    const SF_KEY_INSERT         = 'sfKeyInsert';              ///< The Insert key
    const SF_KEY_DELETE         = 'sfKeyDelete';              ///< The Delete key
    const SF_KEY_ADD            = 'sfKeyAdd';                 ///< The + key
    const SF_KEY_SUBTRACT       = 'sfKeySubtract';            ///< The - key ('minus'; usually from numpad)
    const SF_KEY_MULTIPLY       = 'sfKeyMultiply';            ///< The * key
    const SF_KEY_DIVIDE         = 'sfKeyDivide';              ///< The / key
    const SF_KEY_LEFT           = 'sfKeyLeft';                ///< Left arrow
    const SF_KEY_RIGHT          = 'sfKeyRight';               ///< Right arrow
    const SF_KEY_UP             = 'sfKeyUp';                  ///< Up arrow
    const SF_KEY_DOWN           = 'sfKeyDown';                ///< Down arrow
    const SF_KEY_NUMPAD_0       = 'sfKeyNumpad0';             ///< The numpad 0 key
    const SF_KEY_NUMPAD_1       = 'sfKeyNumpad1';             ///< The numpad 1 key
    const SF_KEY_NUMPAD_2       = 'sfKeyNumpad2';             ///< The numpad 2 key
    const SF_KEY_NUMPAD_3       = 'sfKeyNumpad3';             ///< The numpad 3 key
    const SF_KEY_NUMPAD_4       = 'sfKeyNumpad4';             ///< The numpad 4 key
    const SF_KEY_NUMPAD_5       = 'sfKeyNumpad5';             ///< The numpad 5 key
    const SF_KEY_NUMPAD_6       = 'sfKeyNumpad6';             ///< The numpad 6 key
    const SF_KEY_NUMPAD_7       = 'sfKeyNumpad7';             ///< The numpad 7 key
    const SF_KEY_NUMPAD_8       = 'sfKeyNumpad8';             ///< The numpad 8 key
    const SF_KEY_NUMPAD_9       = 'sfKeyNumpad9';             ///< The numpad 9 key
    const SF_KEY_F1             = 'sfKeyF1';                  ///< The F1 key
    const SF_KEY_F2             = 'sfKeyF2';                  ///< The F2 key
    const SF_KEY_F3             = 'sfKeyF3';                  ///< The F3 key
    const SF_KEY_F4             = 'sfKeyF4';                  ///< The F4 key
    const SF_KEY_F5             = 'sfKeyF5';                  ///< The F5 key
    const SF_KEY_F6             = 'sfKeyF6';                  ///< The F6 key
    const SF_KEY_F7             = 'sfKeyF7';                  ///< The F7 key
    const SF_KEY_F8             = 'sfKeyF8';                  ///< The F8 key
    const SF_KEY_F9             = 'sfKeyF9';                  ///< The F8 key
    const SF_KEY_F10            = 'sfKeyF10';                 ///< The F10 key
    const SF_KEY_F11            = 'sfKeyF11';                 ///< The F11 key
    const SF_KEY_F12            = 'sfKeyF12';                 ///< The F12 key
    const SF_KEY_F13            = 'sfKeyF13';                 ///< The F13 key
    const SF_KEY_F14            = 'sfKeyF14';                 ///< The F14 key
    const SF_KEY_F15            = 'sfKeyF15';                 ///< The F15 key
    const SF_KEY_PAUSE          = 'sfKeyPause';               ///< The Pause key

    /*-------------
     * CSFML Enum
     *-------------
     */

    const UNKNOWN       = -1;                       ///< Unhandled key
    const A             = 0;                        ///< The A key
    const B             = 1;                        ///< The B key
    const C             = 2;                        ///< The C key
    const D             = 3;                        ///< The D key
    const E             = 4;                        ///< The E key
    const F             = 5;                        ///< The F key
    const G             = 6;                        ///< The G key
    const H             = 7;                        ///< The H key
    const I             = 8;                        ///< The I key
    const J             = 9;                        ///< The J key
    const K             = 10;                       ///< The K key
    const L             = 11;                       ///< The L key
    const M             = 12;                       ///< The M key
    const N             = 13;                       ///< The N key
    const O             = 14;                       ///< The O key
    const P             = 15;                       ///< The P key
    const Q             = 16;                       ///< The Q key
    const R             = 17;                       ///< The R key
    const S             = 18;                       ///< The S key
    const T             = 19;                       ///< The T key
    const U             = 20;                       ///< The U key
    const V             = 21;                       ///< The V key
    const W             = 22;                       ///< The W key
    const X             = 23;                       ///< The X key
    const Y             = 24;                       ///< The Y key
    const Z             = 25;                       ///< The Z key
    const ZERO          = 26;                       ///< The 0 key
    const ONE           = 27;                       ///< The 1 key
    const TWO           = 28;                       ///< The 2 key
    const THREE         = 29;                       ///< The 3 key
    const FOUR          = 30;                       ///< The 4 key
    const FIVE          = 31;                       ///< The 5 key
    const SIX           = 32;                       ///< The 6 key
    const SEVEN         = 33;                       ///< The 7 key
    const EIGHT         = 34;                       ///< The 8 key
    const NINE          = 35;                       ///< The 9 key
    const ESCAPE        = 36;                       ///< The Escape key
    const LEFT_CONTROL  = 37;                       ///< The left Control key
    const LEFT_SHIFT    = 38;                       ///< The left Shift key
    const LEFT_ALT      = 39;                       ///< The left Alt key
    const LEFT_SYSTEM   = 40;                       ///< The left OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const RIGHT_CONTROL = 41;                       ///< The right Control key
    const RIGHT_SHIFT   = 42;                       ///< The right Shift key
    const RIGHT_ALT     = 43;                       ///< The right Alt key
    const RIGHT_SYSTEM  = 44;                       ///< The right OS specific key: window (Windows and Linux')'; apple (MacOS X')'; ...
    const MENU          = 45;                       ///< The Menu key
    const LEFT_BRACKET  = 46;                       ///< The [ key
    const RIGHT_BRACKET = 47;                       ///< The ] key
    const SEMICOLON     = 48;                       ///< The ; key
    const COMMA         = 49;                       ///< 'The '; key
    const PERIOD        = 50;                       ///< The . key
    const QUOTE         = 51;                       ///< The ' key
    const SLASH         = 52;                       ///< The / key
    const BACK_SLASH    = 53;                       ///< The \ key
    const TILDE         = 54;                       ///< The ~ key
    const EQUAL         = 55;                       ///< The = key
    const HYPHEN        = 56;                       ///< The - key (hyphen)
    const SPACE         = 57;                       ///< The Space key
    const ENTER         = 58;                       ///< The Enter/Return key
    const BACKSPACE     = 59;                       ///< The Backspace key
    const TAB           = 60;                       ///< The Tabulation key
    const PAGEUP        = 61;                       ///< The Page up key
    const PAGEDOWN      = 62;                       ///< The Page down key
    const END           = 63;                       ///< The End key
    const HOME          = 64;                       ///< The Home key
    const INSERT        = 65;                       ///< The Insert key
    const DELETE        = 66;                       ///< The Delete key
    const ADD           = 67;                       ///< The + key
    const SUBTRACT      = 68;                       ///< The - key ('minus'; usually from numpad)
    const MULTIPLY      = 69;                       ///< The * key
    const DIVIDE        = 70;                       ///< The / key
    const LEFT          = 71;                       ///< Left arrow
    const RIGHT         = 72;                       ///< Right arrow
    const UP            = 73;                       ///< Up arrow
    const DOWN          = 74;                       ///< Down arrow
    const NUMPAD_0      = 75;                       ///< The numpad 0 key
    const NUMPAD_1      = 76;                       ///< The numpad 1 key
    const NUMPAD_2      = 77;                       ///< The numpad 2 key
    const NUMPAD_3      = 78;                       ///< The numpad 3 key
    const NUMPAD_4      = 79;                       ///< The numpad 4 key
    const NUMPAD_5      = 80;                       ///< The numpad 5 key
    const NUMPAD_6      = 81;                       ///< The numpad 6 key
    const NUMPAD_7      = 82;                       ///< The numpad 7 key
    const NUMPAD_8      = 83;                       ///< The numpad 8 key
    const NUMPAD_9      = 84;                       ///< The numpad 9 key
    const F1            = 85;                       ///< The F1 key
    const F2            = 86;                       ///< The F2 key
    const F3            = 87;                       ///< The F3 key
    const F4            = 88;                       ///< The F4 key
    const F5            = 89;                       ///< The F5 key
    const F6            = 90;                       ///< The F6 key
    const F7            = 91;                       ///< The F7 key
    const F8            = 92;                       ///< The F8 key
    const F9            = 93;                       ///< The F8 key
    const F10           = 94;                       ///< The F10 key
    const F11           = 95;                       ///< The F11 key
    const F12           = 96;                       ///< The F12 key
    const F13           = 97;                       ///< The F13 key
    const F14           = 98;                       ///< The F14 key
    const F15           = 99;                       ///< The F15 key
    const PAUSE         = 100;                      ///< The Pause key
}
